load(":defs.bzl", "ng_app", "ng_config")

package(default_visibility = ["//visibility:public"])

# The Angular application
ng_app(
    name = "app",
    project_name = "rdfrontend",
    deps = [
        # "//projects/lib-a",
    ],
)

ng_config(
    name = "ng-config",
)