name: docker-rust
services:
  grpc:
    build:
      context: grpc
      target: final
    environment:
      - PORT=50052
    networks:
      - http-grpc-bridge
    ports:
      - 50052:50052
  grpc-gateway:
    build:
      context: grpc-gateway/docker-gen
      target: final
    environment:
      - PORT=8081
    networks:
      - http-grpc-bridge
    ports:
      - 8081:8081
    depends_on:
      - grpc
    entrypoint: [/app/grpc_gateway, --backend=grpc:50052]

networks:
  http-grpc-bridge: {}