name: docker-rust
services:
  grpc:
    build:
      context: grpc
      target: final
    # environment:
    networks:
      - http-grpc-bridge
    ports:
      - 50050:50052
  grpc-gateway:
    build:
      context: grpc-gateway/docker-gen
      target: final
    # environment:
    networks:
      - http-grpc-bridge
    ports:
      - 8081:80
    depends_on:
      - grpc
    entrypoint: [/app/grpc_gateway, --backend=grpc:50052]

networks:
  http-grpc-bridge: {}