name: docker-rust
services:
  grpc:
    build:
      context: grpc
      target: final
    # environment:
    networks:
      - http-grpc-bridge
    ports:
      - 50051:50051
  grpc-gateway:
    build:
      context: rdproto/grpc-gateway
      target: final
    # environment:
    networks:
      - http-grpc-bridge
    ports:
      - 8081:8081
    depends_on:
      - grpc
    entrypoint: [/app/grpc_gateway, --grpc-server-endpoint=grpc:50051]

networks:
  http-grpc-bridge: {}