name: docker-rust
services:
  grpc:
    build:
      context: grpc
      target: final
    # environment:
    networks:
      - http-grpc-bridge
      - grpc
    ports:
      - 50051:50051
  grpc-gateway:
    build:
      context: rdproto/grpc-gateway
      target: final
    # environment:
    networks:
      - http-grpc-bridge
    ports:
      - 8081:8081
    depends_on:
      - grpc
    entrypoint: [/app/grpc_gateway, --grpc-server-endpoint=grpc:50051]
  grpcui:
    image: fullstorydev/grpcui
    restart: always
    depends_on:
      - grpc
    entrypoint:
      - /bin/grpcui
    networks:
      - grpc
    ports:
      - 8082:8082
    command:
      - -plaintext
      - -use-reflection
      - -vv
      - -port
      - '8082'
      - -bind
      - '0.0.0.0'
      - -debug-client
      - -open-browser=false
      - grpc:50051
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8083:8080
    environment:
      - SWAGGER_JSON=/foo/greeter.swagger.json
    volumes:
      - ./rdproto/grpc-gateway/gen/openapiv2/proto/echochamber/helloworld/v1/:/foo


volumes:
  swagger:
networks:
  http-grpc-bridge: {}
  grpc: {}