name: docker-rust
services:
  grpc:
    image: example-grpc:latest
    # environment:
    networks:
      - http-grpc-bridge
      - grpc
    ports:
      - 50051:50051
    environment:
      - PORT=50051
      - RUST_LOG=info
  grpc-gateway:
    image: example-grpc-gateway:latest
    # environment:
    networks:
      - http-grpc-bridge
      - grpc
    ports:
      - 8081:8081
    depends_on:
      - grpc
    command:
      - --grpc-server-endpoint=grpc:50051
      - --proxy-port=8081
  grpcui:
    image: fullstorydev/grpcui
    restart: always
    depends_on:
      - grpc
    entrypoint:
      - /bin/grpcui
    networks:
      - grpc
    ports:
      - 8082:8082
    command:
      - -plaintext
      - -use-reflection
      - -vv
      - -port
      - '8082'
      - -bind
      - '0.0.0.0'
      - -debug-client
      - -open-browser=false
      - grpc:50051
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8083:8080
    environment:
      - SWAGGER_JSON=/foo/greeter.swagger.json
    volumes:
      - ../../.bazel/bin/bzl-sandbox/rd/proto/echochamber/helloworld/v1/greeter_openapiv2/bzl-sandbox/rd/proto/echochamber/helloworld/v1:/foo

volumes:
  swagger:
networks:
  http-grpc-bridge: {}
  grpc: {}