load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

# @bazel_tools//src/main/protobuf:build_proto
# proto_library(
#     name = "build_proto",
#     srcs = ["some.proto"],
#     deps = ["@bazel_tools//src/main/protobuf:build_proto"],
# )