package(default_visibility = ["//visibility:public"])

package_group(
    name = "docker",
    packages = [
        "//docker/...",
    ],
)

exports_files([
    "docker_run.sh",
    "docker_compose.sh",
])
