[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
log = "0.4.17"
prost = "0.11.9"
tokio = "1.28.1"
tonic = "0.9.2"
tonic-build = "0.9.2"
