load("@rules_buf//buf:defs.bzl", "buf_lint_test")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//bzl-sandbox/rd:internal"])

exports_files(glob([
    "*.proto",
]))