# Building this target results in bazel-bin/examples/node_modules/@myorg/js_lib, so that
# TypeScript and other node programs beneath bazel-bin/examples are able to resolve its location.
# npm_link_package(
#     name = "node_modules/@myorg/js_lib",
#     src = "//ts/examples/js_lib",
#     root_package = "examples",
#     visibility = ["//ts/examples:__subpackages__"],
# )

# npm_link_package(
#     name = "node_modules/@myorg/dts_lib",
#     src = "//ts/examples/dts_lib",
#     root_package = "examples",
#     visibility = ["//ts/examples:__subpackages__"],
# )

# npm_link_package(
#     name = "node_modules/@myorg/deps_lib",
#     src = "//ts/examples/deps_lib",
#     root_package = "examples",
#     visibility = ["//ts/examples:__subpackages__"],
# )

# npm_link_package(
#     name = "node_modules/@myorg/deps_lib_transpiler",
#     src = "//ts/examples/deps_lib_transpiler",
#     root_package = "examples",
#     visibility = ["//ts/examples:__subpackages__"],
# )
